src/Entity/Images.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ImagesRepository")
 */
class Images
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image_name;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Annonces", inversedBy="images")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ann_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImageName(): ?string
    {
        return $this->image_name;
    }

    public function setImageName(string $image_name): self
    {
        $this->image_name = $image_name;

        return $this;
    }

    public function getAnnId(): ?Annonces
    {
        return $this->ann_id;
    }

    public function setAnnId(?Annonces $ann_id): self
    {
        $this->ann_id = $ann_id;

        return $this;
    }
}

src/Controller/AnnonceController.php
<?php

namespace App\Controller;

use DateTime;
use DateTimeZone;
use App\Entity\Images;
use App\Entity\Annonces;
use App\Form\CreerAnnonceType;
use App\Form\ModifAnnonceType;
use App\Form\ContactAnnonceurType;
use App\Repository\AnnoncesRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AnnonceController extends AbstractController
{
    /**
     * Affichage de toutes les annonces
     * 
     * @Route("/annonces", name="annonces")
     */
    public function listAnnonces(Request $request, PaginatorInterface $paginator)
    {
        $annonces_repo = $this->getDoctrine()->getRepository(Annonces::class)->findBy(['ann_a_valider' => false, 'ann_signaler' => false, 'ann_active' => true]);

        $annonces = $paginator->paginate(
            $annonces_repo, // Requête contenant les données à paginer (ici nos annonces)
            $request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
            3 // Nombre de résultats par page
        );

        return $this->render('annonce/index.html.twig', [
            'annonces' => $annonces
        ]);
    }

    /**
     * Affichage d'une annonce précise
     * 
     * @Route("/annonce/{slug}", name="annonce")
     */
    public function displayAnnonce($slug)
    {
        $annonce = $this->getDoctrine()->getRepository(Annonces::class)->findOneBy(['slug' => $slug]);
        $images = $annonce->getImages();

        //Si l'Id de l'utilisateur connecté est égal à l'Id de l'utilisateur-auteur de l'annonce, on affiche l'annonce uniquement pour lui. L'admin du site peut aussi voir l'annonce.
        if ($this->isGranted('ROLE_USER') && $this->getUser() == $annonce->getUsers() || $this->isGranted('ROLE_ADMIN')) {

            return $this->render('annonce/annonce_article.html.twig', [
                'annonce' => $annonce,
                'images' => $images
            ]);
        }

        //Affichage quand aucun utilisateur n'est connecté (affichage public).
        if ($annonce->getAnnAValider()) {
            $this->addFlash(
                'error',
                'Annonce en attente de validation par l\'administrateur.'
            );

            return $this->redirectToRoute('home'); 
        }
        else if ($annonce->getAnnSignaler()) {
            $this->addFlash(
                'error',
                'Annonce en attente de modération par l\'administrateur.'
            );

            return $this->redirectToRoute('home'); 
        }
        else if (!$annonce->getAnnActive()) {
            $this->addFlash(
                'error',
                'Annonce désactivée.'
            );

            return $this->redirectToRoute('home');
        }
        else {
            return $this->render('annonce/annonce_article.html.twig', [
            'annonce' => $annonce
            ]);  
        }
    }

    /**
     * Signaler une annonce
     * 
     * @Route("/signaler-annonce/{id}", name="signaler_annonce")
     */
    public function signalerAnnonce($id)
    {
        $annonce = $this->getDoctrine()->getRepository(Annonces::class)->find($id);

        if ($annonce->getAnnSignaler(true)) {
            $this->addFlash(
                'error',
                'L\'annonce a déjà été signalée à l\'administrateur.'
            );

            return $this->redirectToRoute('home'); 
        }
        else {
            $annonce->setAnnSignaler(true);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($annonce);
            $entityManager->flush();

            $this->addFlash(
                'success',
                'L\'annonce est signalée à l\'administrateur.
                Par sécurité, celle-ci n\'est plus affichée jusqu\'à sa modération.'
            );

            return $this->redirectToRoute('home'); 
        } 
    }

    /**
     * Formulaire pour envoyer un message à l'annonceur
     * 
     * @Route("/annonce/{slug}/contact-annonceur", name="contact_annonceur")
     */
    public function contactAnnonceur(Request $request, \Swift_Mailer $mailer, $slug)
    {
        $form = $this->createForm(ContactAnnonceurType::class);
        $form->handleRequest($request);
        
        $annonce = $this->getDoctrine()->getRepository(Annonces::class)->findOneBy(['slug' => $slug]);
        $emailAnnonceur = $annonce->getUsers()->getEmail();

        if ($form->isSubmitted() && $form->isValid()) {
            $contact = $form->getData();
            if (empty($contact['accept_form'])) {  // Si le champ 'anti-captcha' est vide, on envoie l'email'.
                $this->addFlash(
                    'notice',
                    'Votre message a été envoyé.'
                );

                // do anything else you need here, like send an email
                $message = (new \Swift_Message('Hello Email'))
                ->setFrom('no-reply-proxicar@florentvila.com')
                ->setTo($emailAnnonceur)
                ->setReplyTo($contact['email'])
                ->setSubject('Proxi\'Car - Message concernant votre annonce')
                ->setBody(
                    $this->renderView(
                        // templates/emails/registration.html.twig
                        'emails/contact_mail_annonceur.html.twig',
                        ['titre_annonce' => $annonce->getAnnTitre(), 'name' => $contact['name'], 'email' => $contact['email'], 'message' => $contact['message']]
                    ),
                    'text/html'
                );
                $mailer->send($message);
            }
            else {  // Si le champ 'anti-captcha' est rempli, on n'envoie pas l'email'.
                $this->addFlash(
                'error',
                'Votre message n\'a pas été envoyé.'
                );
            }
            return $this->redirectToRoute('annonce', ['slug' => $slug]);
        }
        
        return $this->render('annonce/contact_annonceur.html.twig', [
            'contactAnnonceurForm' => $form->createView(),
            'annonce' => $annonce
        ]);
    }

    /**
     * Affichage du panneau de Gestion des annonces publiées
     * 
     * @IsGranted("ROLE_USER")
     * 
     * @Route("/gestion-annonces", name="gestion_annonces")
     */
    public function displayAnnManager()
    {
        $userAnnonces = $this->getUser()->getAnnonces();

        return $this->render('account/gestion_annonces.html.twig', [
            'controller_name' => 'Gestion Des Annonces',
            'user_annonces' => $userAnnonces
        ]);
    }

    /**
     * Formulaire de création d'une annonce
     * 
     * @IsGranted("ROLE_USER")
     * 
     * @Route("/creer-annonce", name="creer_annonce")
     */
    public function creerAnnonce(Request $request): Response
    {
        $annonce = new Annonces;

        $form = $this->createForm(CreerAnnonceType::class, $annonce);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $annonce->setAnnDate(new \DateTime('now', new DateTimeZone('Europe/Paris')));
            $annonce->setUsers($this->getUser());

            $images = $form->get('images')->getData();
            
            if (count($images) < 8) {  // Si le nombre d'images est inférieur à 8, on envoie le formulaire
                // Ajout des images
                foreach ($images as $image) {
                    // Stockage sur Disque Dur
                    $fichier = md5(uniqid()).'.'.$image->guessExtension();
                    $image->move($this->getParameter('images_annonce'), $fichier);

                    // Ecriture en Base de Données
                    $img = new Images;
                    $img->setImageName($fichier);
                    $annonce->addImage($img);
                }

                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($annonce);
                $entityManager->flush();

                $this->addFlash(
                    'notice',
                    'L\'annonce a été soumise au modérateur pour validation.'
                );
                
                return $this->redirectToRoute('user_panel');
            }
            else {  // Sinon on regénere la vue avec un message flash et avec la saisie de l'utilisateur conservée
                $formData = $form->getData();

                $this->addFlash(
                    'error',
                    'Vous avez chargé plus de 8 photos. 8 photos maximum autorisées.'
                );

                return $this->render('annonce/creer_annonce.html.twig', [
                    'creerAnnonceForm' => $form->createView(),
                    $formData
                ]);
            }  
        }
        return $this->render('annonce/creer_annonce.html.twig', [
            'creerAnnonceForm' => $form->createView()
        ]);
    }

    /**
     * Formulaire de modification d'une annonce
     * 
     * @IsGranted("ROLE_USER")
     * 
     * @Route("/modif-annonce/{id}", name="modif_annonce")
     */
    public function modifAnnonce(Request $request, $id)
    {
        $annonce = $this->getDoctrine()->getRepository(Annonces::class)->find($id);
                
        $form = $this->createForm(ModifAnnonceType::class, $annonce);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $annonce->setAnnSignaler(false);
            $annonce->setAnnModeree(false);

            // Ajout des nouvelles images
            $images = $form->get('images')->getData();
            foreach ($images as $image) {
                // Stockage sur Disque Dur

templates/annonce/annonce_article.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonce - Proxi'Car{% endblock %}

{% block stylesheets %} 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
    <link rel="stylesheet" href="{{asset('css/flexslider/flexslider.css')}}">
{% endblock %}

{% block body %}
    <div class="container annonce-article-container">
        {% for message in app.flashes('notice') %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}

        {% for message in app.flashes('success') %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}

        {% for message in app.flashes('error') %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
        {% endfor %}

        {% if annonce.annavalider == true %}
            <div class="alert alert-info" role="alert">
                Annonce en attente de validation par l'administrateur.
            </div>
        {% endif %}
        {% if annonce.annsignaler == true %}
            <div class="alert alert-danger" role="alert">
                Annonce en attente de modération par l'administrateur.
            </div>
        {% endif %} 
        {% if annonce.annactive == false %}
            <div class="alert alert-warning" role="alert">
                Annonce inactive.
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-center">{{ annonce.anntitre }}</h1>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <p class="text-center pt-2"> Mise en ligne le {{ annonce.anndate|localizeddate('none', 'none', null, null, 'd MMMM Y') }} | Par: {{ annonce.users.pseudo }}</p>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-12">
                <div id="slider" class="flexslider">
                    <ul class="slides">
                        {% for image in annonce.images %}  
                            <li>
                                <a data-fancybox="gallery" href="{{ asset('uploads/images/featured/'~image.imageName) }}"><img src="{{ asset('uploads/images/featured/'~image.imageName)|imagine_filter('article') }}"></a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>   
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div id="carousel" class="flexslider">
                    <ul class="slides">
                        {% for image in annonce.images %}  
                            <li>
                                <img src="{{ asset('uploads/images/featured/'~image.imageName)|imagine_filter('img_slide') }}">
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-right">
                {% if annonce.annsignaler == true %} 
                    <p>Annonce en attente de modération.</p>
                {% elseif annonce.annmoderee == true %}
                    Annonce modéréé par l'administrateur.
                {% else %}
                    <a class="signaler-annonce" href="{{ path('signaler_annonce', {'id': annonce.id}) }}">Signaler un abus</a>
                {% endif %}
            </div>
        </div>
        <div class="row mt-5 text-center">
            <div class="col-md-12">
                <h1>Description</h1>
                <hr>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-md-12">
                <p>{{ annonce.anncontenu|raw }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <p>Prix: {{ annonce.annprix }} Euros</p>
            </div>
            <div class="col-md-2">
                <p>Année: {{ annonce.anneemodele }}</p> 
            </div>
            <div class="col-md-3"> 
                <p>Kilométrage: {{ annonce.kilometre }} KM</p>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-3">
                <p>Puissance fiscale: {{ annonce.cv }} CV</p>
                <p>Carburant: {{ annonce.carburant }}</p>
                <p>Boite de vitesse: {{ annonce.boitedevitesse }}</p>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-5">
                <p>Région: {{ annonce.region }}</p>
            </div>
            <div class="col-md-5">
                <p>Département: {{ annonce.departement }}</p> 
            </div>
            <div class="col-md-2"> 
                <p>Ville: {{ annonce.ville }}</p>
            </div>
        </div>
        <div class="row my-5 text-center">
            <div class="col-md-6 mb-3">
                <a class="send-message" href="{{ path('contact_annonceur', {'slug': annonce.slug}) }}">Ecrire à l'annonceur</a>
            </div>
            {% if annonce.users.numtel %}
                <div class="col-md-6">
                    <a class="numtel-button" num-user="{{ annonce.users.numtel }}">Voir le N° de téléphone</a>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
    <script src="{{asset('js/jquery.flexslider.js')}}"></script>
    <script src="{{asset('js/carouselCarAnnInit.js')}}"></script>
    <script src="{{asset('js/hideTelNum.js')}}"></script>
{% endblock %}

templates/annonce/contact_annonceur.html.twig
{% extends 'base.html.twig' %}

{% block title %}Envoyer un message - Proxi'Car{% endblock %}

{% block body %}
    <div class="contact-annonceur-background">
        <div class="container contact-annonceur-container">
            <a href="{{ path('annonce', {'slug': annonce.slug}) }}" class="fas fa-angle-left retour mb-3"> Retour à l'annonce</a>
            {{ form_start(contactAnnonceurForm) }}
                <h1 class="text-center">Contacter l'annonceur</h1>
                <hr>
                <div class="no-bot-box">{{ form_row(contactAnnonceurForm.accept_form) }}</div> <!-- Captcha invisible -->
                <div class="form-group">{{ form_row(contactAnnonceurForm.name) }}</div> 
                <div class="form-group">{{ form_row(contactAnnonceurForm.email) }}</div>
                <div class="form-group">{{ form_row(contactAnnonceurForm.message) }}</div>
                <button class="btn btn-lg btn-primary" type="submit">Envoyer</button>
            {{ form_end(contactAnnonceurForm) }}
        </div>
    </div>
{% endblock %}

templates/annonce/creer_annonce.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création de l'annonce{% endblock %}

{% block stylesheets %} 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
{% endblock %}

{% block body %}
    <div class="container creer-annonce-container">
        {% for message in app.flashes('error') %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
        {% endfor %}
        <div class="row">
            <div class="col-md-12">
                <a href="{{ path('user_panel') }}" class="fas fa-angle-left retour"> Retour</a>
                <h1 class="text-center">Création de l'annonce</h1>
                <hr>
                {{ form_start(creerAnnonceForm) }}
                    <div class="form-group">{{ form_row(creerAnnonceForm.ann_titre) }}</div>
                    <div class="form-group">{{ form_row(creerAnnonceForm.marque) }}</div>
                    <div class="form-group">{{ form_row(creerAnnonceForm.modele) }}</div> 
                    <div class="form-group">{{ form_row(creerAnnonceForm.annee_modele) }}</div>
                    <div class="form-group">
                        {{ form_label(creerAnnonceForm.kilometre) }}
                        <div class="input-group">
                            {{ form_widget(creerAnnonceForm.kilometre) }}
                            <div class="input-group-append">
                                <span class="input-group-text">KM</span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">{{ form_row(creerAnnonceForm.carburant) }}</div>
                    <div class="form-group">{{ form_row(creerAnnonceForm.boite_de_vitesse) }}</div>
                    <div class="form-group">
                        {{ form_label(creerAnnonceForm.ann_prix) }}
                        <div class="input-group">
                            {{ form_widget(creerAnnonceForm.ann_prix) }}
                            <div class="input-group-append">
                                <span class="input-group-text">€</span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form_label(creerAnnonceForm.cv) }}
                        <div class="input-group">
                            {{ form_widget(creerAnnonceForm.cv) }}
                            <div class="input-group-append">
                                <span class="input-group-text">CV</span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">{{ form_row(creerAnnonceForm.region) }}</div>
                    <div class="form-group">{{ form_row(creerAnnonceForm.departement) }}</div>
                    <div class="form-group">{{ form_row(creerAnnonceForm.ville) }}</div>
                    <div class="form-group images">{{ form_row(creerAnnonceForm.images) }}</div>
                    <div class="form-group">{{ form_row(creerAnnonceForm.ann_contenu) }}</div>
                    <button class="btn btn-lg btn-primary" type="submit">Publier</button>
                {{ form_end(creerAnnonceForm) }}
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
    <script src="{{asset('js/jsUpload.js')}}"></script>
{% endblock %}

templates/annonce/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonces - Proxi'Car{% endblock %}

{% block stylesheets %} 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
{% endblock %}

{% block body %}
    <div class="container annonces-container">
        <h1 class="text-center section-heading">Nos Annonces</h1>
        <hr>

        {% for annonce in annonces|sort %}
            <div class="card mb-3 shadow">
                <div class="row no-gutters">
                    {% for image in annonce.images %}
                        {% if loop.first %}
                            <div class="col-md-4">
                                <a data-fancybox="gallery" href="{{ asset('uploads/images/featured/'~image.imageName) }}"><img class="card-img-top w-100 d-block" src="{{ asset('uploads/images/featured/'~image.imageName) }}"></a>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <div class="col-md-8">
                        <div class="card-body">
                            <p class="card-text text-center date-publication">Publiée le {{ annonce.anndate|localizeddate('none', 'none', null, null, 'd MMMM Y') }}</p> 
                            <p><a class="card-title link" href="{{ path('annonce', {'slug': annonce.slug}) }}">{{ annonce.anntitre }}</a></p> 
                            <p class="card-text">{{ annonce.kilometre }} KM</p>
                            <p class="card-text">Prix: {{ annonce.annprix }} Euros</p>
                            <p class="card-text">Année: {{ annonce.anneemodele }}</p>
                            <p class="card-text">Boîte de vitesse: {{ annonce.boitedevitesse }}</p>
                            <p class="card-text">Energie: {{ annonce.carburant }}</p>
                            <p class="card-text">Région: {{ annonce.region }} | Département: {{ annonce.departement }} | {{ annonce.ville }}</p>
                            <a class="voir-annonce" href="{{ path('annonce', {'slug': annonce.slug}) }}">Voir l'annonce</a> 
                        </div>
                    </div> 
                </div>
            </div>
        {% endfor %}
        {{ knp_pagination_render(annonces) }}
    </div>
{% endblock %} 

{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
{% endblock %}

templates/annonce/modif_annonce.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification de l'annonce{% endblock %}

{% block stylesheets %} 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
{% endblock %}

{% block body %}
    <div class="container modif-annonce-container">
        <div class="row">
            <div class="col-md-12">
                <a href="{{ path('gestion_annonces') }}" class="fas fa-angle-left retour"> Retour</a>
                <h1 class="text-center">Modification de l'annonce</h1>
                <hr>
                {{ form_start(modifAnnonceForm) }}
                    <div class="form-group">{{ form_row(modifAnnonceForm.ann_titre) }}</div>
                    <div class="form-group">{{ form_row(modifAnnonceForm.marque) }}</div>
                    <div class="form-group">{{ form_row(modifAnnonceForm.modele) }}</div> 
                    <div class="form-group">{{ form_row(modifAnnonceForm.annee_modele) }}</div>
                    <div class="form-group">
                        {{ form_label(modifAnnonceForm.kilometre) }}
                        <div class="input-group">
                            {{ form_widget(modifAnnonceForm.kilometre) }}
                            <div class="input-group-append">
                                <span class="input-group-text">KM</span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">{{ form_row(modifAnnonceForm.carburant) }}</div>
                    <div class="form-group">{{ form_row(modifAnnonceForm.boite_de_vitesse) }}</div>
                    <div class="form-group">
                        {{ form_label(modifAnnonceForm.ann_prix) }}
                        <div class="input-group">
                            {{ form_widget(modifAnnonceForm.ann_prix) }}
                            <div class="input-group-append">
                                <span class="input-group-text">€</span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form_label(modifAnnonceForm.cv) }}
                        <div class="input-group">
                            {{ form_widget(modifAnnonceForm.cv) }}
                            <div class="input-group-append">
                                <span class="input-group-text">CV</span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">{{ form_row(modifAnnonceForm.region) }}</div>
                    <div class="form-group">{{ form_row(modifAnnonceForm.departement) }}</div>
                    <div class="form-group">{{ form_row(modifAnnonceForm.ville) }}</div>
                    <div class="form-group images">{{ form_row(modifAnnonceForm.images) }}</div>
                    {% for image in annonce.images %}
                        <div class="form-group">
                            <a data-fancybox="gallery" href="{{ asset('uploads/images/featured/'~image.imageName) }}"><img src="{{ asset('uploads/images/featured/'~image.imageName)|imagine_filter('carre') }}" alt="Image"></a>
                            <button class="btn btn-lg btn-danger delete-image mt-3 ml-3" data-url="{{ path('supprimer_image', {'id': image.id}) }}" type="submit">Supprimer</button>
                        </div> 
                    {% endfor %}
                    <div class="form-group">{{ form_row(modifAnnonceForm.ann_contenu) }}</div>
                    <button class="btn btn-lg btn-primary" type="submit">Enregistrer les modifications</button>
                {{ form_end(modifAnnonceForm) }}
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
    <script src="{{asset('js/ajaxCallImages.js')}}"></script>
    <script src="{{asset('js/jsUpload.js')}}"></script>
{% endblock %}